### ISSUE TITLE
The website of Sim10k dataset is down. 

### ISSUE THREAD

**Issue by ljpadam** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#12]
Hi,
Thanks for your awesome codes! The websit of Sim10k dataset is down. Could you share the Sim10k data by google drive or baidu drive?

**Comment by krumo** [comment]
Hi @ljpadam , you could find the dataset at [here](https://fcav.engin.umich.edu/projects/driving-in-the-matrix).

**Comment by ljpadam** [comment]
> Hi @ljpadam , you could find the dataset at [here](https://fcav.engin.umich.edu/projects/driving-in-the-matrix).

Yes, thank you for your help.
