### ISSUE TITLE
Can't reproduce the result

### ISSUE THREAD

**Issue by sheepooo** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#16]
Hello, I run the test_net.py with the pre-trained model you provided (https://polybox.ethz.ch/index.php/s/OgkNFJHVkEscTO0) , but my AP50 is only 0.21. I can't find the reason, could you help me?

**Comment by krumo** [comment]
Hi, I would suggest that you should check the test data is generated correctly and the pretrained model weight is loaded correctly.
