### ISSUE TITLE
How to resume my training

### ISSUE THREAD

**Issue by yutongred** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#17]
Now I got model_0042500.pth and dont't know how to resume my training from here

**Comment by yutongred** [comment]
Now I got model_0042500.pth and dont't know how to resume my training from here

**Comment by krumo** [comment]
Because this repo is implemented based on maskrcnn-benchmark, please consider to follow [this issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/558) to resume your training.

**Comment by yutongred** [comment]
thanks figured it out
