### ISSUE TITLE
cityscape dataset

### ISSUE THREAD

**Issue by GiovanniPasq** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#20]
Hi, thanks for your work. Can you share the processed versions of cityscape and foggy cityscape datasets to reproduce the results?

**Comment by krumo** [comment]
Hi @GiovanniPasq ,
Unfortunately I don't have the right to redistribute these two datasets. You could consider to apply for the permission at [Cityscapes website](https://www.cityscapes-dataset.com/). 

Plus, I didn't do any special processing to these two datasets. You could download our pretrained weights and perform an evaluation to reproduce our results.
