### ISSUE TITLE
rpn loss

### ISSUE THREAD

**Issue by Feobi1999** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#21]
When calculating the loss of the rpn part, how do you deal with the  label of the target domain? I  found you treat source and target domain data equally？I only notice you process the target domain label when calculate the loss of roi head.
Looking forward to your reply

**Comment by SkeletonOne** [comment]
https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/pull/3#issuecomment-555979375

**Comment by krumo** [comment]
Thanks for your interest! When computing rpn loss, the labels of target domain are ignored at [here](https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/f75c583f8dbe6d7a2a87272fde3b794773c38527/maskrcnn_benchmark/modeling/rpn/loss.py#L64).
