### ISSUE TITLE
img_head and ins_head

### ISSUE THREAD

**Issue by Feobi1999** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#22]
Have you tried res50 for sim10--cityscape experiment? Could you show the results of the experiment? I did the experiment but I only observed that img_head has good performance, but ins_head does not seem to have much effect.

**Comment by krumo** [comment]
Hi! Yes I tried res50 for sim10--cityscapes setting and you could find the config file in this repo. According to my experience, ins_head would also contribute to the performance. However, ins_head may have a different convergence speed compared to img_head and a good result might not happen at the final step. You coud consider to test all checkpoints to see how the performance of instance-level adaptation changes.

**Comment by Feobi1999** [comment]
Would you like to share the Res50 result for sim to cityscape dataset？
