### ISSUE TITLE
Image level adaptation with FPN

### ISSUE THREAD

**Issue by gabridego** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#26]
Hello @krumo , thanks for the great work! I am trying to use your project with a ResNet backbone with a feature pyramid network on top, I would like to ask you if you have any clue about how to apply the domain discriminator at the image level in this case, as the backbone returns feature maps of different sizes, and it is not possible to simply concatenate them. I've noticed that it is stated that `DomainAdaptationModule` works for both FPN and non-FPN and that a boolean `USE_FPN` parameter is mentioned but not used, maybe you already thought of an expected behavior?
https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/2f7892d1a22b0ba53f1dd807da15be36a7bbfea5/maskrcnn_benchmark/modeling/da_heads/da_heads.py#L15-L21
Thanks!

**Comment by krumo** [comment]
Hi, thanks for your interest! Yes, we tried combining the domain adaptation module with FPN, the design and the experimental results have been released in our IJCV paper [Scale-Aware Domain Adaptive Faster R-CNN](https://link.springer.com/article/10.1007/s11263-021-01447-x). You could also check our implementation in [sa-da-faster](https://github.com/yuhuayc/sa-da-faster).
