### ISSUE TITLE
convert image

### ISSUE THREAD

**Issue by newera-001** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#27]
FileNotFoundError: [Errno 2] No such file or directory: './datasets/caronly_filtered_gtFine_val.json'

**Comment by krumo** [comment]
Hi, this error is caused by the fact that you don't generate the required *caronly_filtered_gtFine_val.json* in the correct location. Please consider to use the scripts in 'tools/cityscapes' and 'tools/kitti' to generate the corresponding files.

**Comment by newera-001** [comment]
got it think u



At 2021-07-26 10:23:32, "Haoran Wang" ***@***.***> wrote:

Hi, this error is caused by the fact that you don't generate the required caronly_filtered_gtFine_val.json in the correct location. Please consider to use the scripts in 'tools/cityscapes' and 'tools/kitti' to generate the corresponding files.
