### ISSUE TITLE
Do you have plan to make more DA configs?

### ISSUE THREAD

**Issue by MinsuKim3095** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#28]
Hi. Thanks for your great work.
I want more DA configs for train. such as faster_rcnn_x_101, r_101.
Do you have plan to make these things?

**Comment by krumo** [comment]
Hi, I would refer you to the newer version of this paper [Scale-Aware Domain Adaptive Faster R-CNN](https://link.springer.com/article/10.1007/s11263-021-01447-x), which includes more DA settings. The corresponding code is also open sourced at [sa-da-faster](https://github.com/yuhuayc/sa-da-faster).

**Comment by MinsuKim3095** [comment]
@krumo Thanks for reply.
