### ISSUE TITLE
what does losses mean?

### ISSUE THREAD

**Issue by MinsuKim3095** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#29]
Hello. I checked your new git.
Thanks for your great work.

My question is the meaning of many losses.

- loss / 
- loss_classifier /
-  loss_box_reg / 
- loss_objectness / 
- loss_rpn_box_reg / 
- loss_da_image / 
- loss_da_instance / 
- loss_da_consistency

where can I found detailed explanation of these loss?

**Comment by krumo** [comment]
Sorry for the late reply. 

The *loss_classifier*, *loss_box_reg*, *loss_objectness*, *loss_rpn_box_reg* are losses defined in the paper [Faster R-CNN](https://arxiv.org/pdf/1506.01497.pdf), which corresponds to the classification loss of bbox head, bbox regression loss of bbox head, binary classification loss of rpn, bbox regression loss of rpn. 

The *loss_da_image*, *loss_da_instance*, *loss_da_consistency* are losses defined in the paper [Domain Adaptive Faster R-CNN](https://arxiv.org/pdf/1803.03243.pdf), which corresponds to the loss for image-level domain adaptation, loss for instance-level domain adaptation and the consistency regularization for aligning the prediction of image-level domain discriminator and instance-level domain discriminator.

I would refer you to the original papers to find a more detailed explanation about the losses mentioned above.
