### ISSUE TITLE
cannot import name '_C' from 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by Azann** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#31]
ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (/home/crx/zhanzan/Domain-Adaptive-Faster-RCNN-PyTorch_5/maskrcnn_benchmark/__init__.py)

I can run train_net.py in terminal successfully. 
But I can't run this in pycharm.

**Comment by Azann** [comment]
I found out where is my problem. The reason is that Before I run the code, I don't complile the environment I need successfully.

**Comment by chengxy1998** [comment]
File "/home/data/Lm/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.DOMAIN_ADAPTATION_ON'

Who can tell me how to solve this problem, I will be very grateful

**Comment by krumo** [comment]
> File "/home/data/Lm/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b raise KeyError("Non-existent config key: {}".format(full_key)) KeyError: 'Non-existent config key: MODEL.DOMAIN_ADAPTATION_ON'
> 
> Who can tell me how to solve this problem, I will be very grateful

This error generally means that you don't compile this project successfully. Please follow the instructions in [INSTALL.md](https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/master/INSTALL.md) to compile this project first.

**Comment by leoliu37** [comment]
I solve the problem. Actually, you need to compile it in the folder './Domain-Adaptive-Faster-RCNN-Pytorch'. 
Good wishes to you.
