### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by chengxy1998** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#32]
I installed ninja on the server, but there was an error when running pycharm. Strangely, I didn't have this error when running on the server

**Comment by krumo** [comment]
Hi, I didn't try running this project with PyCharm. Thus, unfortunately I could only give some guess about the error. Did you check you load the correct environment to run this project in PyCharm?
