### ISSUE TITLE
How to get Images with bounding box predictions ?

### ISSUE THREAD

**Issue by tilahun12** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#34]

**Comment by krumo** [comment]
Hi, there is a simple demo for result visualization at [Mask_R-CNN_demo.ipynb](https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/master/demo/Mask_R-CNN_demo.ipynb). You could consider to follow it to visualize results on your own data.
