### ISSUE TITLE
how to solve the img's label  when resize img?

### ISSUE THREAD

**Issue by shishi-jie** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#35]
File "D:\000_zhuang\DA_F_RCNN_torch_c\maskrcnn_benchmark\data\transforms\transforms.py", line 60, in __call__
    target = target.resize(image.size)
AttributeError: 'list' object has no attribute 'resize'

**Comment by krumo** [comment]
Hi, you could consider to follow https://github.com/facebookresearch/maskrcnn-benchmark/issues/876 to rename all `self.transforms` to `self._transforms` in [coco.py](https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/master/maskrcnn_benchmark/data/datasets/coco.py).
