### ISSUE TITLE
when i run the code some bugs appear.i don't how to handle it.Thank you in advance

### ISSUE THREAD

**Issue by shishi-jie** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#36]
File "D:\000_zhuang\DA_F_RCNN_torch_c\maskrcnn_benchmark\structures\boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: Not compiled with GPU support

i can't   from maskrcnn_benchmark import _C     and  there isn't _C

**Comment by shishi-jie** [comment]
one thing should be add that there isnot setup.py in maskrcnn_benchmark

**Comment by krumo** [comment]
It seems that you are running this project under Windows. Unfortunately I don't have a windows PC with a cuda-support GPUs and I cannot give you detailed help. It seems that you don't compile this project successfully. I would suggest you look at issues posted in the [maskrccn_benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) project like https://github.com/facebookresearch/maskrcnn-benchmark/issues/523 to find the possible solutions. The `setup.py` is located at `https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/master/setup.py`.
