### ISSUE TITLE
为什么testnet.py测试结果（AP,AP50,AP75,APm,APs,APl）都趋于0?

### ISSUE THREAD

**Issue by 906096481** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#37]
比如（'AP',2.2241e-05）

**Comment by krumo** [comment]
This is a duplicate issue of https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/issues/38. I will close this issue now. More discussion about this question could be found in that issue.
