### ISSUE TITLE
i can't reach the pretrained model

### ISSUE THREAD

**Issue by ReynLi** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#39]
the link of pretrained model is invalid, could you upload it again

**Comment by krumo** [comment]
Hi, thanks for your attention. Unfortunately I also don't have the access to the previous pretrained model. Thus, I retrain the model under the same setting and update the README with a new download link. You can access to it through [here](https://drive.google.com/drive/folders/1d5jnKE1_Mu2skgHCiGv0PD9-ixxr2rvF?usp=sharing).
