### ISSUE TITLE
The link of  the pretrained model is invalid

### ISSUE THREAD

**Issue by ninishu** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#45]
Hello! Can you upload the pretrained model again? Thank you！

**Comment by krumo** [comment]
Hi, thanks for your attention. Unfortunately I also don't have the access to the previous pretrained model. Thus, I retrain the model under the same setting and update the README with a new download link. You can access to it through [here](https://drive.google.com/drive/folders/1d5jnKE1_Mu2skgHCiGv0PD9-ixxr2rvF?usp=sharing).
