### ISSUE TITLE
IndexError: list index out of range, when run the test_net.py

### ISSUE THREAD

**Issue by WanyiLi** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#5]
when I run the test_net.py via using the following cmd, "IndexError: list index out of range" occurs.
used cmd:
python tools/test_net.py --config_file "configs/da_faster_rcnn/e2e_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml" MODEL.WEIGHT trainedmodels/model_cst.pth
File "/home/casia_robot_lwy/Documents/code_cv/da_object_detetion/Domain-Adaptive-Faster-RCNN-PyTorch-master/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 464, in __getitem__
    selected_polygons.append(self.polygons[i])

occured error:
IndexError: list index out of range

errored image is 462/500 in val set of cityscapes, specifically, it is lindau_000020_000019_leftImg8bit.png

**Comment by krumo** [comment]
Hi, actually I don't encounter this error. It seems that the annotation file has some mistakes. Please check whether your data is complete and your annotations are generated correctly.
