### ISSUE TITLE
 the result map 41.0 is with FPN or not

### ISSUE THREAD

**Issue by mickeyding** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#8]
First of all, thanks for your excellent work！

May I ask you whether the result map 41.0 is with FPN or not since it is too much better than paper's.
I see the configuration in log.txt is without the FPN.

Thanks again

**Comment by krumo** [comment]
@mickeyding The result of map 41.0 is got without FPN. The result reported in the paper is based on VGG-16 backbone, while the result reported in this repo is based on ResNet-50 backbone. I consider the use of different backbone could explain the performance difference.
