### ISSUE TITLE
This implementation is quit diffrent from the original paper

### ISSUE THREAD

**Issue by Liyw979** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#9]
This implementation is based on maskrcnn-benchmark, from which the faster rcnn is not the same in the original paper, for example
1 origin backbone: vgg16, here: resnet
2 origin roi pooler: roi pool, here: roi align
3 origin roi feature: 2 mlp, here ResNet50Conv5
and so on
These difference is default in the maskrcnn-benchmark.
People who refers to this implementation so really pay attention to these difference.

**Comment by krumo** [comment]
@liyiwei979621500 I totally agree with you. The setting used in the original paper (like VGG16 and roi pooling) is not popular anymore. I think it is rational to update the training/testing configurations in alignment with the state-of-the-art object detection framework. If you would like to run the DA Faster RCNN in the original setting, I would suggest you implement the necessary components by yourself or use the [Caffe version](https://github.com/yuhuayc/da-faster-rcnn) or [Caffe2 version](https://github.com/krumo/Detectron-DA-Faster-RCNN) of DA Faster RCNN. Both ways would be easy.
